lib/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',)

urlpatterns += patterns('',
                        # Examples:
                        # url(r'^$', 'pyWriter.views.home', name='home'),
                        # url(r'^pyWriter/', include('pyWriter.foo.urls')),

                        # Uncomment the admin/doc line below to enable admin documentation:
                        # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

                        # Uncomment the next line to enable the admin:
                        url(r'^admin/', include(admin.site.urls)),
                        )

if settings.DEBUG:
    urlpatterns += patterns('',
                           (r'^library/(?P<path>.*)$', 'django.views.static.serve', {
                            'document_root': settings.MEDIA_ROOT}),
                            )

urlpatterns += patterns('',
                        url(r'^$', 'pyWriter.lib.apps.story.views.index'),
                        )

urlpatterns += patterns('',
                        url(r'^tinymce/', include('tinymce.urls')),
                        )

urlpatterns += patterns('',
                        url(
                        r'^login/$', 'pyWriter.lib.apps.login.views.login_view',
                        name="login_view"),
                        url(r'^logout/$',
                            'pyWriter.lib.apps.login.views.logout_view'),
                        url(
                        r'^signup/$', 'pyWriter.lib.apps.login.views.create_user_view',
                        name="signup"),
                        )

urlpatterns += patterns('',
                        url(
                        r'^scene/list/$', 'pyWriter.lib.apps.story.views.scenelist',
                        name="list_scene"),
                        url(
                        r'^sortscenes/$', 'pyWriter.lib.apps.story.views.scenesort',
                        name="sort_scenes"),
                        url(
                        r'^scene/add/$', 'pyWriter.lib.apps.story.views.scene',
                        name="add_scene"),
                        url(r'^scene/(?P<scene>\d+)/$',
                            'pyWriter.lib.apps.story.views.scene', name="edit_scene"),
                        )
urlpatterns += patterns('',
                        url(
                        r'^story/list/$', 'pyWriter.lib.apps.story.views.storylist',
                        name="list_stories"),
                        url(
                        r'^story/add/$', 'pyWriter.lib.apps.story.views.story',
                        name="add_story"),
                        url(r'^story/(?P<story>[\w-]+)/$',
                            'pyWriter.lib.apps.story.views.story', name="edit_story"),
                        url(r'^story/activate/(?P<story>\d+)/$',
                            'pyWriter.lib.apps.story.views.activate_story', name="activate_story"),
                        url(r'^story/print/(?P<story>\d+)/$',
                            'pyWriter.lib.apps.story.views.print_story', name="print_story"),
                        url(r'^story/reallyprint/(?P<story>\d+)/$',
                            'pyWriter.lib.apps.story.views.really_print_story', name="really_print_story"),
                        url(r'^story/print/epub/(?P<story>\d+)/$',
                            'pyWriter.lib.apps.epub.views.print_epub', name="print_epub"),
                        )
urlpatterns += patterns('',
                        url(
                        r'^chapter/list/$', 'pyWriter.lib.apps.story.views.chapterlist',
                        name="list_chapters"),
                        url(
                        r'^sortchapters/$', 'pyWriter.lib.apps.story.views.chaptersort',
                        name="sort_chapters"),
                        url(
                        r'^chapter/add/$', 'pyWriter.lib.apps.story.views.chapter',
                        name="add_chapter"),
                        url(r'^chapter/(?P<chapter>\d+)/$',
                            'pyWriter.lib.apps.story.views.chapter', name="edit_chapter"),
                        )
urlpatterns += patterns('',
                        url(
                        r'^character/list/$', 'pyWriter.lib.apps.story.views.characterlist',
                        name="list_characters"),
                        url(
                        r'^character/add/$', 'pyWriter.lib.apps.story.views.character',
                        name="add_character"),
                        url(r'^character/(?P<character>\d+)/$',
                            'pyWriter.lib.apps.story.views.character', name="edit_character"),
                        url(r'^character/preview/(?P<character>\d+)/$',
                            'pyWriter.lib.apps.story.views.preview_character', name="preview_character"),
                        url(r'^timeline/character/(?P<character>\d+)/$',
                            'pyWriter.lib.apps.story.views.timeline_character', name="timeline_character"),
                        )
urlpatterns += patterns('',
                        url(
                        r'^location/list/$', 'pyWriter.lib.apps.story.views.locationlist',
                        name="list_locations"),
                        url(
                        r'^location/add/$', 'pyWriter.lib.apps.story.views.location',
                        name="add_location"),
                        url(r'^location/(?P<location>\d+)/$',
                            'pyWriter.lib.apps.story.views.location', name="edit_location"),
                        url(r'^location/preview/(?P<location>\d+)/$',
                            'pyWriter.lib.apps.story.views.preview_location', name="preview_location"),
                        )
urlpatterns += patterns('',
                        url(
                        r'^artifact/list/$', 'pyWriter.lib.apps.story.views.artifactlist',
                        name="list_artifacts"),
                       url(
                           r'^artifact/add/$', 'pyWriter.lib.apps.story.views.artifact',
                           name="add_artifact"),
                           url(r'^artifact/(?P<artifact>\d+)/$',
                               'pyWriter.lib.apps.story.views.artifact', name="edit_artifact"),
                           url(r'^artifact/preview/(?P<artifact>\d+)/$',
                               'pyWriter.lib.apps.story.views.preview_artifact', name="preview_artifact"),
                        )


if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
   )

lib/apps/story/models.py
from django.db import models
from django.contrib.auth.models import User

from django.template.defaultfilters import slugify

from django import forms
import math

MOTIVATION_LIST = [
    'Time to start writing',
    'You\'ve barely started!',
    'Time to get writing?',
    'You\'re getting somewhere now',
    'Nearly halfway there!',
    'The midway point',
    'It\'s all downhill from here',
    'Three quarters of the way there',
    'Almost at the finish',
    'Last push and you\'ll be done',
    'You\'ve done it!'
    ];


class Genre(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField(blank=True)

    def __unicode__(self):
        return self.name


class Story(models.Model): 
    user = models.ForeignKey(User)
    storyslug = models.SlugField(null=True, blank=True)
    title = models.CharField(max_length=256,  help_text="Short and snappy? Verbose yet informative?")
    author = models.CharField(max_length=128, help_text="A pseudonym? Remember, you can always change this later")
    synopsis = models.TextField(blank=True, help_text="A brief summary, your salespitch. What are the main themes/points of your story?")
    genre = models.ForeignKey(Genre, null=True, blank=True, help_text="If a genre is not listed then feel free to get in touch with suggestions")
    fiction = models.BooleanField(default=True, help_text="Leave this blank if you are writing a factual account. If it's a tissue of lies however...")
    cover = models.ImageField(
        upload_to='covers/%Y/%m/%d', null=True, blank=True, help_text="A picture is worth a thousand words. This doesn't mean we will add this to your word count")
    registered_access = models.BooleanField(default=False, help_text="When published make this story available to registered users")
    public_access = models.BooleanField(default=False, help_text="When published, make this story available to the public (Overrides registered user access)")
    
    def save(self, *args, **kwargs):
		uniquestring = "%s %s" % (self.title, self.author)
		self.storyslug = slugify(uniquestring)
		super(Story, self).save(*args, **kwargs)
		
    @property
    def get_chapters(self):
        chapters = Chapter.objects.all().filter(story=self).order_by('weight')          
        return chapters
        
    @property
    def get_chapter_count(self):
        chapters = Chapter.objects.all().filter(story=self)
        return len(chapters)
        
    @property
    def get_scenes(self):
        chapters = self.get_chapters
        scenes = []
        for chap in chapters:
            scenes += Scene.objects.filter(chapter=chap).order_by('order')
        return scenes
    
    @property
    def get_characters(self):
        scenes = self.get_scenes
        charlist = []
        for s in scenes:
            charlist += Character.objects.filter(scene=s)
        charlist = set(charlist) # converts the charlist to distinct values
        return charlist
    
    @property
    def get_locations(self):
        scenes = self.get_scenes
        locations = []
        for s in scenes:
            locations += Location.objects.filter(scene=s)
        locations = set(locations)
        return locations

    @property
    def get_artifacts(self):
        scenes = self.get_scenes
        artifacts = []
        for s in scenes:
            artifacts += Artifact.objects.filter(scene=s)
        artifact = set(artifacts)
        return artifacts

    @property
    def get_stats(self):
        stats = {}
        scenes = []
        wc = 0
        wt = 0
        scenes = self.get_scenes
        for s in scenes:
           wc = wc+s.word_count
           wt = wt+s.word_target
        stats['wordcount'] = wc
        stats['wordtarget'] = wt
        try:
            stats['percentage'] = int((float(wc) / float(wt)) * 100)
        except:
            stats['percentage'] = 0
        
        return stats
    
    @property
    def get_motivation(self):
        stats = self.get_stats
        percentage = stats['percentage']
        motivation = int(math.floor(int(percentage) * 0.1))
        
        if motivation >= 10:
            motivation = 10
        return MOTIVATION_LIST[motivation]
    
    def __unicode__(self):
        return self.title
	


class Chapter(models.Model):
    user = models.ForeignKey(User)
    story = models.ForeignKey(Story)
    title = models.CharField(max_length=256)
    weight = models.IntegerField(default=1)

    @property
    def get_scenes(self):
        scenes = Scene.objects.filter(chapter=self).order_by('order')
        return scenes
    
    @property
    def get_scene_count(self):
        scenes = Scene.objects.filter(chapter=self)
        return len(scenes)
        
    def __unicode__(self):
        return self.title


class Scene(models.Model):
    OUTLINE = 'OL'
    DRAFT = 'DR'
    FIRSTEDIT = 'FE'
    SECONDEDIT = 'SE'
    DONE = 'DO'

    SUBPLOT = 'SP'
    MAINPLOT = 'MP'

    PLOT_CHOICES = (
        (MAINPLOT, 'Main plot'),
        (SUBPLOT, 'Subplot'),
    )

    STATUS_CHOICES = (
        (OUTLINE, 'Outline'),
        (DRAFT, 'Draft'),
        (FIRSTEDIT, '1st Edit'),
        (SECONDEDIT, '2nd Edit'),
        (DONE, 'Complete'),
    )

    user = models.ForeignKey(User)
    name = models.CharField(max_length=255)
    importance = models.CharField(
        max_length=15, choices=PLOT_CHOICES, default=SUBPLOT)
    status = models.CharField(
        max_length=15, choices=STATUS_CHOICES, default=OUTLINE)
    perspective = models.ForeignKey(
        'Character', related_name='perspective', null=True, blank=True)
    chapter = models.ForeignKey(Chapter, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    characters = models.ManyToManyField('Character', null=True, blank=True)
    location = models.ManyToManyField('Location', null=True, blank=True)
    artifacts = models.ManyToManyField('Artifact', null=True, blank=True)
    content = models.TextField(null=True, blank=True)
    word_target = models.IntegerField(blank=True, default=1000)
    word_count = models.IntegerField(blank=True, null=True)
    order = models.IntegerField(default=1)
    scene_start_time = models.DateTimeField(null=True, blank=True)
    scene_end_time = models.DateTimeField(null=True, blank=True)

    @property
    def get_percentage_complete(self):
        return int((float(self.word_count) / float(self.word_target)) * 100)

    @property
    def get_character_count(self):
        charlist = Character.objects.filter(scene=self)
        return len(charlist)

    @property
    def get_location_count(self):
        locationlist = Location.objects.filter(scene=self)
        return len(locationlist)

    @property
    def get_scene_location(self):
        scene_location = Location.objects.filter(scene=self)
        if scene_location:
            return scene_location[0]
        else:
            return "an unknown location"
        
    @property
    def get_artifact_count(self):
        artifactlist = Artifact.objects.filter(scene=self)
        return len(artifactlist)

    def __unicode__(self):
        return self.name


class Character(models.Model):
    user = models.ForeignKey(User)
    firstname = models.CharField(max_length=255)
    middlename = models.CharField(max_length=255, blank=True)
    lastname = models.CharField(max_length=255, blank=True)
    nicknames = models.TextField(null=True, blank=True)
    major_character = models.BooleanField(default=False)
    role = models.CharField(max_length=255, null=True, blank=True, 
        help_text="The role this character might play. Is he lover, father, killer, chauffeur, detective, soldier, wizard?")
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(
        upload_to='characters/%Y/%m/%d', null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField(null=True, blank=True)
    
    def get_timeline(self):
        t = Scene.objects.all().filter(characters=self).order_by('scene_start_time')
        
        return t;
        
    def __unicode__(self):
        return "%s %s" % (self.firstname, self.lastname)


class Artifact(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(
        upload_to='artifacts/%Y/%m/%d', null=True, blank=True)
    owner = models.ForeignKey(Character, null=True, blank=True)
    location = models.ForeignKey('Location', null=True, blank=True)
    date_of_construction = models.DateField(null=True, blank=True)
    date_of_destruction = models.DateField(null=True, blank=True)
    
    def __unicode__(self):
        return self.name


class Location(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    date_of_construction = models.DateField(null=True, blank=True)
    date_of_destruction = models.DateField(null=True, blank=True)
    image = models.ImageField(
        upload_to='locations/%Y/%m/%d', null=True, blank=True)

    def __unicode__(self):
        return self.name

import feedparser
def Getfeed(url):
    d = feedparser.parse(url)
    return d.entries;

def Getissues():
    import urllib, json
    url = "https://api.github.com/repos/garhol/pywriter/issues"
    try:
        myresponse = urllib.urlopen(url)
        jsonResponse = json.loads(myresponse.read())
    except:
        jsonResponse = None
    return jsonResponse
    

from django.db.models.signals import pre_save
from django.dispatch import receiver


@receiver(pre_save, sender=Scene)
def create_wordcount(instance, **kwargs):
    words = instance.content.split()
    instance.word_count = len(words)


@receiver(pre_save, sender=Scene)
def create_narrator(instance, **kwargs):
    if not instance.pk:

templates/story/_story_details_form.html
{% load story_tags %}
{% load widget_tweaks %}

<form id='story_details_form' enctype="multipart/form-data" action="" class='form' method="post">
    <div class='row'>
        {% csrf_token %}
        <div class='span4'>
            <div class='padded'>
            {% for field in form %}
                    {% if field.name == "genre" %}
                    
                        <button type="submit" class="btn btn-primary">Save changes</button>
                        <a href='/story/list/' class="btn">Cancel</a>
                    
            </div>
        </div>
        <div class='span8'>
            <div class='padded'>
                    {% endif %}
                    {{ field.errors }}
                    
                    {% if field|is_checkbox %}
                        <label class="checkbox" for="{{ field.auto_id }}">
                            {{ field }}
                            {{ field.label }}
                            
                        </label>
                        <span class='help-block'>{{ field.help_text }}</span>
                    {% else %}
                    <div class='control-group'>

                        
                        <label for="{{ field.auto_id }}" class='control-label'>{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                        <div class='controls'>

                            {% if field|is_textarea %}

                                {{ field|attr:"rows:4"|attr:"class:span4" }}

                            {% elif field|is_textinput %}

                                {{ field|attr:"class:span4" }}

                            {% elif field|is_file %}
                                {{ field|attr:"class:button" }}
                            {% else %}
                                {{ field }}
                            {% endif %}
                        </div>
                        <span class="help-block">{{ field.help_text }}</span>

                    </div>
                    {% endif %}
            {% endfor %}
            </div>
        </div>
    </div>
    
</form>

templates/story/artifact.html
{% extends "base-templates/base.html" %}
{% load thumbnail %}
{% load story_tags %}

{% block "css" %}
    {{block.super}}
    <link rel="stylesheet" href="{{ STATIC_URL }}js/jquery-ui-1.10.0/css/smoothness/jquery-ui-1.10.0.custom.min.css">
{% endblock %}
{% block "javascript" %}
    {{block.super}}
    <script type="text/javascript" src='{{ STATIC_URL }}js/jquery-ui-1.10.0/js/jquery-ui-1.10.0.custom.min.js'></script>
    <script type="text/javascript">
    	$(function(){

    		$("#id_date_of_construction, #id_date_of_destruction").datepicker();

    	})
    </script>
{% endblock %}

{% block "main" %}
	{{ block.super }}
	<section class='row' id='{{ artifact_action }}'>
    <div class='span12 pod'>
            {% generic_one_column_form form %}
    </div>
</section>
{% endblock %}

templates/story/base_edit_page.html
{% extends "base-templates/base.html" %}

{% block "css" %}
    {{block.super}}   
{% endblock %}

{% block "javascript" %}
    {{block.super}}
    <script type="text/javascript" src='{{ STATIC_URL }}js/jquery-ui-1.10.0/js/jquery-ui-1.10.0.custom.min.js'></script>
    <script type="text/javascript" src='{{ STATIC_URL}}js/story_edit.js'></script>
{% endblock %}

{% load story_tags %}

{% block "main" %}
<section class='row' id='{{ story_action }}'>
    <div class='span12 pod'>
            {% story_form form %}
    </div>
</section>
{% endblock "main" %}

templates/story/chapter.html
{% extends "story/base_edit_page.html" %}
{% load thumbnail %}
{% load story_tags %}

{% block "main" %}
	<section class='row'>
    <div class='span12 pod'>
            {% generic_one_column_form form %}
    </div>
	</section>
{% endblock "main" %}

templates/story/character.html
{% extends "base-templates/base.html" %}
{% load thumbnail %}
{% load story_tags %}

{% block "css" %}
    {{block.super}}
    <link rel="stylesheet" href="{{ STATIC_URL }}js/jquery-ui-1.10.0/css/smoothness/jquery-ui-1.10.0.custom.min.css">
{% endblock %}

{% block "javascript" %}
    {{block.super}}
    <script type="text/javascript" src='{{ STATIC_URL }}js/jquery-ui-1.10.0/js/jquery-ui-1.10.0.custom.min.js'></script>
    <script type="text/javascript">
    	$(function(){

    		$("#id_date_of_birth, #id_date_of_death").datepicker();

    	})
    </script>
{% endblock %}

{% block "main" %}
	{{ block.super }}
	<section class='row' id='{{ story_action }}'>
    <div class='span12 pod'>
            {% generic_one_column_form form %}
    </div>
</section>
{% endblock %}

templates/story/location.html
{% extends "base-templates/base.html" %}
{% load thumbnail %}
{% load story_tags %}

{% block "css" %}
    {{block.super}}
    <link rel="stylesheet" href="{{ STATIC_URL }}js/jquery-ui-1.10.0/css/smoothness/jquery-ui-1.10.0.custom.min.css">
{% endblock %}

{% block "javascript" %}
    {{block.super}}
    <script type="text/javascript" src='{{ STATIC_URL }}js/jquery-ui-1.10.0/js/jquery-ui-1.10.0.custom.min.js'></script>
    <script type="text/javascript">
    	$(function(){

    		$("#id_date_of_construction, #id_date_of_destruction").datepicker();

    	})
    </script>
{% endblock %}

{% block "main" %}
	{{ block.super }}
	<section class='row' id='{{ location_action }}'>
    <div class='span12 pod'>
            {% generic_one_column_form form %}
    </div>
</section>
{% endblock %}

templates/story/preview_artifact.html
{% extends "base-templates/preview.html" %}
{% load thumbnail %}

{% block "content" %}
    {% if artifact.image %}
        <img class="previewThumb" src="{% thumbnail artifact.image 120x120 %}"  alt="{{artifact}}" />
    {% else %}
        <img class="previewThumb noPreview" src="{{ STATIC_URL }}library/images/icons/artifact-icon.jpg" alt="{{artifact}}" />
    {% endif %}
     <h3 class="previewName" style="margin-bottom:0.5em;">{% if artifact.name %}{{artifact.name}}{% endif %}</h3>
        {% if artifact.owner %}<p><strong>Owner:</strong> {{artifact.owner}}</p>{% endif %}
        {% if artifact.location %}<p><strong>Location:</strong> {{artifact.location}}</p>{% endif %}
    <div class="previewParticulars">
        {% if artifact.description %}<p><strong>Desc:</strong> {{artifact.description}}</p>{% endif %}
    </div>
    <p style="clear:left; margin-top:10px; float:left;"><a href="/artifact/{{artifact.pk}}"  target="_parent" class="button medium red">Edit</a></p>
{% endblock %}

templates/story/preview_character.html
{% extends "base-templates/preview.html" %}
{% load thumbnail %}

{% block "content" %}
    {% if character.image %}
        <img class="previewThumb" src="{% thumbnail character.image 120x120 %}"  alt="{{character}}" />
    {% else %}
        <img class="previewThumb noPreview" src="{{ STATIC_URL }}library/images/icons/nocharacter.png" alt="{{character}}" />
    {% endif %}
    <h3 class="previewName">{% if character.firstname %}{{character.firstname}}{% endif %}{% if character.middlename %} {{character.middlename}}{% endif %}{% if character.lastname %} {{character.lastname}}{% endif %}</h3>
    {% if character.nicknames %}
    <h4 class="previewAlias">aka {{character.nicknames}}</h4>{% endif %}
        {% if character.date_of_birth %}<p><strong>Born:</strong> {{character.date_of_birth}}</p>{% endif %}
        {% if character.date_of_death %}<p><strong>Died:</strong> {{character.date_of_death}}</p>{% endif %}
    <div class="previewParticulars">
        {% if character.description %}<p><strong>Desc:</strong> {{character.description}}</p>{% endif %}
        {% if character.bio %}<p><strong>Bio:</strong> {{character.bio}}</p>{% endif %}
    </div>
    <p style="clear:left; margin-top:10px; float:left;"><a href="/character/{{character.pk}}" target="_parent" class="button medium red">Edit</a></p>
{% endblock %}

templates/story/preview_location.html
{% extends "base-templates/preview.html" %}
{% load thumbnail %}

{% block "content" %}
    {% if location.image %}
        <img class="previewThumb" src="{% thumbnail location.image 120x120 %}"  alt="{{location}}" />
    {% else %}
        <img class="previewThumb noPreview" src="{{ STATIC_URL }}library/images/icons/location-icon.png" alt="{{location}}" />
    {% endif %}
    <h3 class="previewName">{% if location.name %}{{location.name}}{% endif %}</h3>
    <div class="previewParticulars">
        {% if location.description %}<p><strong>Desc:</strong> {{location.description}}</p>{% endif %}
    </div>
    <p style="clear:left; margin-top:10px; float:left;"><a href="/location/{{location.pk}}" target="_parent" class="button medium red">Edit</a></p>
{% endblock %}

templates/story/print_story.html
{% extends "base-templates/base.html" %}
{% load thumbnail %}

{% block "css" %}
    {{block.super}}   
{% endblock %}

{% block "javascript" %}
    {{block.super}}
    <script type="text/javascript" src='{{ STATIC_URL }}js/jquery-ui-1.10.0/js/jquery-ui-1.10.0.custom.min.js'></script>
{% endblock %}

{% load story_tags %}

{% block "main" %}
<div class="row">
<section class="span8">
    <div class='padded pod'>
    <div class="printversion">
        <h1>{{story.title}}</h1>
        <h2>{{story.author}}</h2>
        <hr />
        {% if story.get_chapters %}
            <h4>Index:</h4>
            <ul>
            {% for c in story.get_chapters %}

                {% if c.get_scenes %}
                    <li>{{c}}</li>
                    <ul>
                    {% for sc in c.get_scenes %}
                        <li>{{ sc }}</li>
                    {% endfor %}
                    </ul>
                {% endif %}
            {% endfor %}
            </ul>
        {% endif %}
        <hr />
        {% if story.get_chapters %}
            {% for c in story.get_chapters %}
                {% if c.get_scenes %}
                    <h4>{{c}}</h4>
                    <hr />
                    {% for sc in c.get_scenes %}
                        <h5>{{sc}}</h5>
                        <p>{{ sc.content|safe}}</p>
                        <hr />
                    {% endfor %}
                {% endif %}
            {% endfor %}
        {% endif %}

    </div>
</section>
<section class="span4">
<div class="padded pod">
    <h3>Preview</h3>
    <p>This is a preview of your current story</p>
    <p>Printable version <a href="/story/reallyprint/{{story.pk}}">here</a></p>
    <p>Please check and then <a href="/story/print/epub/{{story.pk}}" class="btn btn-success" >create epub</a></p>
</div>
</section>
</div>
{% endblock "main" %}


{% block "rh" %}
    {{block.super}}

{% if story.cover %}
        <img  src="{% thumbnail story.cover 200x200 %}"  alt="{{story}}" class="characterImage" />
{% endif %}
        
{% if story.get_chapters %}
    <h3>Chapters in this story</h3>
    <p>
    {% for c in story.get_chapters %}
        {{ c }}
        <br />
    {% endfor %}
    </p>
{% endif %}
{% if story.get_scenes %}
    <h3>Scenes in this story</h3>
    <p>
    {% for s in story.get_scenes %}
        {{ s }}
        <br />
    {% endfor %}
    </p>
{% endif %}

<h3>Stats:</h3>
<p>You have written {{ story.get_stats.wordcount }} out of {{ story.get_stats.wordtarget }} words.</p>
<p>{{ story.get_stats.percentage }}% complete - <span class="motivation">{{story.get_motivation}}</span></p>

{% if stats %}
<h3>Scenes:</h3>
{% for s in stats.scenes %}
    <p>{{s}}: {{s.word_count}}/{{s.word_target}}words</p>
    
{% endfor %}
<h4>Total:</h4>
<p>{{stats.wordcount}} words completed.<br />Target words = {{stats.wordtarget}}</p>
<h2>{{stats.percentage}}%</h2>
{% endif %}
<a href="/story/print/{{story.pk}}">Print this story</a>
{% if printversion %}
<a href="/library/epub/{{story.pk}}/{{story.title}}.epub">Download epub (iBook)</a>
<a href="/library/epub/{{story.pk}}/{{story.title}}.mobi">Download mobi (Kindle)</a>
{% endif %}
{% endblock %}

templates/story/scene.html
{% extends "base-templates/base.html" %}
{% load thumbnail %}

{% block "css" %}
    {{block.super}}
    <link rel="stylesheet" href="{{ STATIC_URL }}js/jquery-ui-1.10.0/css/smoothness/jquery-ui-1.10.0.custom.min.css">
{% endblock %}

{% block "javascript" %}
    {{block.super}}
    <script type="text/javascript" src='{{ STATIC_URL }}js/jquery-ui-1.10.0/js/jquery-ui-1.10.0.custom.min.js'></script>
    <script type="text/javascript" src='{{ STATIC_URL}}js/scene_edit.js'></script>
{% endblock %}

{% load story_tags %}

{% block "main" %}
    {{ block.super }}
<section class='row' id='{{ scene_action }}'>
    <div class='span12 pod'>
            {% scene_form form %}
    </div>
</section>

{% endblock "main" %}