lib/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',)

urlpatterns += patterns('',
                        # Examples:
                        # url(r'^$', 'pyWriter.views.home', name='home'),
                        # url(r'^pyWriter/', include('pyWriter.foo.urls')),

                        # Uncomment the admin/doc line below to enable admin documentation:
                        # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

                        # Uncomment the next line to enable the admin:
                        url(r'^admin/', include(admin.site.urls)),
                        )

if settings.DEBUG:
    urlpatterns += patterns('',
                           (r'^library/(?P<path>.*)$', 'django.views.static.serve', {
                            'document_root': settings.MEDIA_ROOT}),
                            )

urlpatterns += patterns('',
                        url(r'^$', 'pyWriter.lib.apps.story.views.index'),
                        )

urlpatterns += patterns('',
                        url(r'^tinymce/', include('tinymce.urls')),
                        )

urlpatterns += patterns('',
                        url(
                        r'^login/$', 'pyWriter.lib.apps.login.views.login_view',
                        name="login_view"),
                        url(r'^logout/$',
                            'pyWriter.lib.apps.login.views.logout_view'),
                        url(
                        r'^signup/$', 'pyWriter.lib.apps.login.views.create_user_view',
                        name="signup"),
                        )

urlpatterns += patterns('',
                        url(
                        r'^scene/list/$', 'pyWriter.lib.apps.story.views.scenelist',
                        name="list_scene"),
                        url(
                        r'^sortscenes/$', 'pyWriter.lib.apps.story.views.scenesort',
                        name="sort_scenes"),
                        url(
                        r'^scene/add/$', 'pyWriter.lib.apps.story.views.scene',
                        name="add_scene"),
                        url(r'^scene/(?P<scene>\d+)/$',
                            'pyWriter.lib.apps.story.views.scene', name="edit_scene"),
                        )
urlpatterns += patterns('',
                        url(
                        r'^story/list/$', 'pyWriter.lib.apps.story.views.storylist',
                        name="list_stories"),
                        url(
                        r'^story/add/$', 'pyWriter.lib.apps.story.views.story',
                        name="add_story"),
                        url(r'^story/(?P<story>[\w-]+)/$',
                            'pyWriter.lib.apps.story.views.story', name="edit_story"),
                        url(r'^story/activate/(?P<story>\d+)/$',
                            'pyWriter.lib.apps.story.views.activate_story', name="activate_story"),
                        url(r'^story/print/(?P<story>\d+)/$',
                            'pyWriter.lib.apps.story.views.print_story', name="print_story"),
                        url(r'^story/reallyprint/(?P<story>\d+)/$',
                            'pyWriter.lib.apps.story.views.really_print_story', name="really_print_story"),
                        url(r'^story/print/epub/(?P<story>\d+)/$',
                            'pyWriter.lib.apps.epub.views.print_epub', name="print_epub"),
                        )
urlpatterns += patterns('',
                        url(
                        r'^chapter/list/$', 'pyWriter.lib.apps.story.views.chapterlist',
                        name="list_chapters"),
                        url(
                        r'^sortchapters/$', 'pyWriter.lib.apps.story.views.chaptersort',
                        name="sort_chapters"),
                        url(
                        r'^chapter/add/$', 'pyWriter.lib.apps.story.views.chapter',
                        name="add_chapter"),
                        url(r'^chapter/(?P<chapter>\d+)/$',
                            'pyWriter.lib.apps.story.views.chapter', name="edit_chapter"),
                        )
urlpatterns += patterns('',
                        url(
                        r'^character/list/$', 'pyWriter.lib.apps.story.views.characterlist',
                        name="list_characters"),
                        url(
                        r'^character/add/$', 'pyWriter.lib.apps.story.views.character',
                        name="add_character"),
                        url(r'^character/(?P<character>\d+)/$',
                            'pyWriter.lib.apps.story.views.character', name="edit_character"),
                        url(r'^character/preview/(?P<character>\d+)/$',
                            'pyWriter.lib.apps.story.views.preview_character', name="preview_character"),
                        url(r'^timeline/character/(?P<character>\d+)/$',
                            'pyWriter.lib.apps.story.views.timeline_character', name="timeline_character"),
                        )
urlpatterns += patterns('',
                        url(
                        r'^location/list/$', 'pyWriter.lib.apps.story.views.locationlist',
                        name="list_locations"),
                        url(
                        r'^location/add/$', 'pyWriter.lib.apps.story.views.location',
                        name="add_location"),
                        url(r'^location/(?P<location>\d+)/$',
                            'pyWriter.lib.apps.story.views.location', name="edit_location"),
                        url(r'^location/preview/(?P<location>\d+)/$',
                            'pyWriter.lib.apps.story.views.preview_location', name="preview_location"),
                        )
urlpatterns += patterns('',
                        url(
                        r'^artifact/list/$', 'pyWriter.lib.apps.story.views.artifactlist',
                        name="list_artifacts"),
                       url(
                           r'^artifact/add/$', 'pyWriter.lib.apps.story.views.artifact',
                           name="add_artifact"),
                           url(r'^artifact/(?P<artifact>\d+)/$',
                               'pyWriter.lib.apps.story.views.artifact', name="edit_artifact"),
                           url(r'^artifact/preview/(?P<artifact>\d+)/$',
                               'pyWriter.lib.apps.story.views.preview_artifact', name="preview_artifact"),
                        )


if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
   )

lib/apps/story/models.py
from django.db import models
from django.contrib.auth.models import User

from django.template.defaultfilters import slugify

from django import forms
import math

MOTIVATION_LIST = [
    'Time to start writing',
    'You\'ve barely started!',
    'Time to get writing?',
    'You\'re getting somewhere now',
    'Nearly halfway there!',
    'The midway point',
    'It\'s all downhill from here',
    'Three quarters of the way there',
    'Almost at the finish',
    'Last push and you\'ll be done',
    'You\'ve done it!'
    ];


class Genre(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField(blank=True)

    def __unicode__(self):
        return self.name


class Story(models.Model): 
    user = models.ForeignKey(User)
    storyslug = models.SlugField(null=True, blank=True)
    title = models.CharField(max_length=256,  help_text="Short and snappy? Verbose yet informative?")
    author = models.CharField(max_length=128, help_text="A pseudonym? Remember, you can always change this later")
    synopsis = models.TextField(blank=True, help_text="A brief summary, your salespitch. What are the main themes/points of your story?")
    genre = models.ForeignKey(Genre, null=True, blank=True, help_text="If a genre is not listed then feel free to get in touch with suggestions")
    fiction = models.BooleanField(default=True, help_text="Leave this blank if you are writing a factual account. If it's a tissue of lies however...")
    cover = models.ImageField(
        upload_to='covers/%Y/%m/%d', null=True, blank=True, help_text="A picture is worth a thousand words. This doesn't mean we will add this to your word count")
    registered_access = models.BooleanField(default=False, help_text="When published make this story available to registered users")
    public_access = models.BooleanField(default=False, help_text="When published, make this story available to the public (Overrides registered user access)")
    
    def save(self, *args, **kwargs):
		uniquestring = "%s %s" % (self.title, self.author)
		self.storyslug = slugify(uniquestring)
		super(Story, self).save(*args, **kwargs)
		
    @property
    def get_chapters(self):
        chapters = Chapter.objects.all().filter(story=self).order_by('weight')          
        return chapters
        
    @property
    def get_chapter_count(self):
        chapters = Chapter.objects.all().filter(story=self)
        return len(chapters)
        
    @property
    def get_scenes(self):
        chapters = self.get_chapters
        scenes = []
        for chap in chapters:
            scenes += Scene.objects.filter(chapter=chap).order_by('order')
        return scenes
    
    @property
    def get_characters(self):
        scenes = self.get_scenes
        charlist = []
        for s in scenes:
            charlist += Character.objects.filter(scene=s)
        charlist = set(charlist) # converts the charlist to distinct values
        return charlist
    
    @property
    def get_locations(self):
        scenes = self.get_scenes
        locations = []
        for s in scenes:
            locations += Location.objects.filter(scene=s)
        locations = set(locations)
        return locations

    @property
    def get_artifacts(self):
        scenes = self.get_scenes
        artifacts = []
        for s in scenes:
            artifacts += Artifact.objects.filter(scene=s)
        artifact = set(artifacts)
        return artifacts

    @property
    def get_stats(self):
        stats = {}
        scenes = []
        wc = 0
        wt = 0
        scenes = self.get_scenes
        for s in scenes:
           wc = wc+s.word_count
           wt = wt+s.word_target
        stats['wordcount'] = wc
        stats['wordtarget'] = wt
        try:
            stats['percentage'] = int((float(wc) / float(wt)) * 100)
        except:
            stats['percentage'] = 0
        
        return stats
    
    @property
    def get_motivation(self):
        stats = self.get_stats
        percentage = stats['percentage']
        motivation = int(math.floor(int(percentage) * 0.1))
        
        if motivation >= 10:
            motivation = 10
        return MOTIVATION_LIST[motivation]
    
    def __unicode__(self):
        return self.title
	


class Chapter(models.Model):
    user = models.ForeignKey(User)
    story = models.ForeignKey(Story)
    title = models.CharField(max_length=256)
    weight = models.IntegerField(default=1)

    @property
    def get_scenes(self):
        scenes = Scene.objects.filter(chapter=self).order_by('order')
        return scenes
    
    @property
    def get_scene_count(self):
        scenes = Scene.objects.filter(chapter=self)
        return len(scenes)
        
    def __unicode__(self):
        return self.title


class Scene(models.Model):
    OUTLINE = 'OL'
    DRAFT = 'DR'
    FIRSTEDIT = 'FE'
    SECONDEDIT = 'SE'
    DONE = 'DO'

    SUBPLOT = 'SP'
    MAINPLOT = 'MP'

    PLOT_CHOICES = (
        (MAINPLOT, 'Main plot'),
        (SUBPLOT, 'Subplot'),
    )

    STATUS_CHOICES = (
        (OUTLINE, 'Outline'),
        (DRAFT, 'Draft'),
        (FIRSTEDIT, '1st Edit'),
        (SECONDEDIT, '2nd Edit'),
        (DONE, 'Complete'),
    )

    user = models.ForeignKey(User)
    name = models.CharField(max_length=255)
    importance = models.CharField(
        max_length=15, choices=PLOT_CHOICES, default=SUBPLOT)
    status = models.CharField(
        max_length=15, choices=STATUS_CHOICES, default=OUTLINE)
    perspective = models.ForeignKey(
        'Character', related_name='perspective', null=True, blank=True)
    chapter = models.ForeignKey(Chapter, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    characters = models.ManyToManyField('Character', null=True, blank=True)
    location = models.ManyToManyField('Location', null=True, blank=True)
    artifacts = models.ManyToManyField('Artifact', null=True, blank=True)
    content = models.TextField(null=True, blank=True)
    word_target = models.IntegerField(blank=True, default=1000)
    word_count = models.IntegerField(blank=True, null=True)
    order = models.IntegerField(default=1)
    scene_start_time = models.DateTimeField(null=True, blank=True)
    scene_end_time = models.DateTimeField(null=True, blank=True)

    @property
    def get_percentage_complete(self):
        return int((float(self.word_count) / float(self.word_target)) * 100)

    @property
    def get_character_count(self):
        charlist = Character.objects.filter(scene=self)
        return len(charlist)

    @property
    def get_location_count(self):
        locationlist = Location.objects.filter(scene=self)
        return len(locationlist)

    @property
    def get_scene_location(self):
        scene_location = Location.objects.filter(scene=self)
        if scene_location:
            return scene_location[0]
        else:
            return "an unknown location"
        
    @property
    def get_artifact_count(self):
        artifactlist = Artifact.objects.filter(scene=self)
        return len(artifactlist)

    def __unicode__(self):
        return self.name


class Character(models.Model):
    user = models.ForeignKey(User)
    firstname = models.CharField(max_length=255)
    middlename = models.CharField(max_length=255, blank=True)
    lastname = models.CharField(max_length=255, blank=True)
    nicknames = models.TextField(null=True, blank=True)
    major_character = models.BooleanField(default=False)
    role = models.CharField(max_length=255, null=True, blank=True, 
        help_text="The role this character might play. Is he lover, father, killer, chauffeur, detective, soldier, wizard?")
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(
        upload_to='characters/%Y/%m/%d', null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField(null=True, blank=True)
    
    def get_timeline(self):
        t = Scene.objects.all().filter(characters=self).order_by('scene_start_time')
        
        return t;
        
    def __unicode__(self):
        return "%s %s" % (self.firstname, self.lastname)


class Artifact(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(
        upload_to='artifacts/%Y/%m/%d', null=True, blank=True)
    owner = models.ForeignKey(Character, null=True, blank=True)
    location = models.ForeignKey('Location', null=True, blank=True)
    date_of_construction = models.DateField(null=True, blank=True)
    date_of_destruction = models.DateField(null=True, blank=True)
    
    def __unicode__(self):
        return self.name


class Location(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    date_of_construction = models.DateField(null=True, blank=True)
    date_of_destruction = models.DateField(null=True, blank=True)
    image = models.ImageField(
        upload_to='locations/%Y/%m/%d', null=True, blank=True)

    def __unicode__(self):
        return self.name

import feedparser
def Getfeed(url):
    d = feedparser.parse(url)
    return d.entries;

def Getissues():
    import urllib, json
    url = "https://api.github.com/repos/garhol/pywriter/issues"
    try:
        myresponse = urllib.urlopen(url)
        jsonResponse = json.loads(myresponse.read())
    except:
        jsonResponse = None
    return jsonResponse
    

from django.db.models.signals import pre_save
from django.dispatch import receiver


@receiver(pre_save, sender=Scene)
def create_wordcount(instance, **kwargs):
    words = instance.content.split()
    instance.word_count = len(words)


@receiver(pre_save, sender=Scene)
def create_narrator(instance, **kwargs):
    if not instance.pk:

templates/form_partials/_generic_one_column_form.html
{% load story_tags %}
{% load widget_tweaks %}
<form enctype="multipart/form-data" action="" class='form' method="post">
    <div class='row'>
        {% csrf_token %}
        <div class='span12'>
            <div class='padded'>
                {% for field in form %}
                {{ field.errors }}                    
                    {% if field|is_checkbox %}
                        <label class="checkbox" for="{{ field.auto_id }}">
                            {{ field }}
                            {{ field.label }}
                            
                        </label>
                        <span class='help-block'>{{ field.help_text }}</span>
                    {% else %}
                    <div class='control-group {% if field.errors %}errorinput{% endif %}'>

                        
                        <label for="{{ field.auto_id }}" class='control-label {% if field.field.required %}required{% endif %}'>{{ field.label }}</label>
                        <div class='controls'>

                            {% if field|is_textarea %}

                                {{ field|attr:"rows:4"|attr:"class:span4" }}

                            {% elif field|is_textinput %}

                                {{ field|attr:"class:span4" }}

                            {% elif field|is_file %}
                                {{ field|attr:"class:button" }}
                            {% else %}
                                {{ field }}
                            {% endif %}
                        </div>
                        <span class="help-block">{{ field.help_text }}</span>

                    </div>
                    {% endif %}
            {% endfor %}

            <button type="submit" class="btn btn-primary">Save changes</button>
            <a href='javascript:history.back()' class="btn">Cancel</a>
            </div>
        </div>
    </div>
    
</form>

templates/form_partials/_story_details_form.html
{% load story_tags %}
{% load widget_tweaks %}

<form id='story_details_form' enctype="multipart/form-data" action="" class='form' method="post">
{% csrf_token %}
    <div class='row'>
        <div class='span12'>
            <header class='padded'>
                <h2>Story Details</h2>
            </header>
        </div>
    </div>
    <div class='row'>
       <div class='span3'>
            <div class='padded first'>
                <fieldset>
                    <legend>Jacket</legend>
                    <div class="control-group">

                        <label for="{{ form.cover.html_name }}" {% if form.cover.field.required %}class="required"{% endif %}>Upload Image</label>
                        
                        <div class="controls">
                            {{ form.cover }}    
                        </div>
                        <span class="help-block">{{ form.cover.help_text }}</span>
                    </div>
                </fieldset>
                
            </div>
       </div> 
       <div class='span4'>
            <fieldset>
                    <legend>Basic Info</legend>
                <div class="control-group {% if form.title.errors %} errorinput{% endif %}">                  
                        {{ form.title.errors }}
                    <label for="id_title" class="control-label {% if form.title.field.required %}required{% endif %}">{{ form.title.label }}</label>
                        <div class="controls">                     
                            {{ form.title|attr:"class:span4" }}
                        </div>
                        <span class="help-block">{{ form.title.help_text }}</span>
                </div>
                <div class="control-group {% if form.author.errors %} errorinput{% endif %}">
                        {{ form.author.errors }}
                    <label for="id_author" class="control-label {% if form.author.field.required %}required{% endif %}">Author</label>
                        <div class="controls">                     
                            {{ form.author|attr:"class:span4" }}
                        </div>
                        <span class="help-block">{{ form.author.help_text }}</span>
                </div>
                <div class="control-group {% if form.synopsis.errors %} errorinput{% endif %}">
                        {{ form.synopsis.errors }}
                    <label for="id_synopsis" class="control-label {% if form.synopsis.field.required %}required{% endif %}">Synopsis</label>
                        <div class="controls">                     
                            {{ form.synopsis|attr:"rows:4"|attr:"class:span4" }}
                        </div>
                        <span class="help-block">{{ form.synopsis.help_text }}</span>
                </div>
                
            </fieldset> 
        </div>

        <div class='span5'>
            <div class='padded last'>
                <fieldset>
                    <legend>Classification</legend>
                    <div class="control-group {% if form.genre.errors %} errorinput{% endif %}">
                        {{ form.genre.errors }}
                        <label for="id_genre" class="control-label{% if form.genre.field.required %}required{% endif %}">Genre</label>
                        <div class="controls">
                            {{ form.genre }}                            
                        </div>
                        <span class="help-block">{{ form.genre.help_text }}</span>
                    </div>

                    {{ form.fiction.errors }}
                    <label class="checkbox {% if form.fiction.field.required %}required{% endif %}" for="id_fiction">
                                {{ form.fiction }}
                                Fiction
                    </label>
                    <span class="help-block">{{ form.fiction.help_text }}</span>
                </fieldset>
                <fieldset>
                    <legend>Access</legend>
                    {{ form.registered_access.errors}}
                    <label class="checkbox {% if form.registered_access.field.required %}required{% endif %}" for="id_registered_access">
                        {{ form.registered_access}}
                        Registered access
                    </label>
                    <span class="help-block">{{ form.registered_access.help_text }}</span>
                        
                    {{ form.public_access.errors}}
                    <label class="checkbox {% if form.publis_access.field.required %}required{% endif %}" for="id_public_access">
                        {{ form.public_access}}
                        Public Access
                    </label>
                    <span class="help-block">{{ form.public_access.help_text }}</span>
                </fieldset>
                <div class='submit'>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                    <a href='/story/list/' class="btn">Cancel</a>
                    <a href="/story/print/{{s.id}}" class="btn">Print preview</a>
                </div>
                
                
            </div>
        </div>
    </div>  <!-- end row -->
</form>

templates/form_partials/_story_facets_form.html
<section id='story-facets'>
	<article class='row story-facet' id='story-chapters'>
		<div class='span12 pod'>
			<div class='padded'>
				<header>
					<h2>Chapters <small>[drag to reorder]</small><a href='/chapter/add' class='pull-right btn btn-success'>Add Chapter</a></h2>
				</header>
				<ul class='sortable tabular'>
                    {% if s.get_chapters %}
                        {% for c in s.get_chapters %}
                            <li>{{c}} <span>{% if c.get_scene_count > 0 %}<a href='#'>View {{c.get_scene_count}} Scenes</a>{% endif %}</span><span><a href='/scene/add/'>Add Scene</a></span></li>
                        {% endfor %}
                    {% endif %}
				</ul>
			</div>	
		</div>
	</article>

	<article class='row story-facet' id='story-characters'>
		<div class='span12 pod'>
			<div class='padded'>
				<header>
					<h2>Characters<a href='#' class='pull-right btn btn-success'>Add Character</a></h2>
				</header>
				<ul class='tabular'>
                    {% if s.get_characters %}
                        {% for character in s.get_characters %}
                            <li>{{character}} <span><a href='#'>View</a></span><span><a href='/character/{{character.id}}'>Edit</a></span></li>
                        {% endfor %}
                    {% endif %}
				</ul>
			</div>	
		</div>
	</article>
	<article class='row story-facet' id='story-locations'>
		<div class='span12 pod'>
			<div class='padded'>
				<header>
					<h2>Locations<a href='#' class='pull-right btn btn-success'>Add Location</a></h2>
				</header>
				<ul class='tabular'>
                    {% if s.get_locations %}
                        {% for location in s.get_locations %}
                            <li>{{location}} <span><a href='#'>View</a></span><span><a href='/location/{{location.id}}'>Edit</a></span></li>
                        {% endfor %}
                    {% endif %}
				</ul>
			</div>	
		</div>
	</article>
	<article class='row story-facet' id='story-artifacts'>
		<div class='span12 pod'>
			<div class='padded'>
				<header>
					<h2>Artifacts<a href='#' class='pull-right btn btn-success'>Add Artifact</a></h2>
				</header>
				<ul class='tabular'>
                    {% if s.get_artifacts %}
                        {% for artifact in s.get_artifacts %}
                            <li>{{artifact}} <span><a href='#'>View</a></span><span><a href='/artifact/{{artifact.id}}'>Edit</a></span></li>
                        {% endfor %}
                    {% endif %}
				</ul>
			</div>	
		</div>
	</article>
</section>